Rebranding
GeoWerkstatt/geopilot pull request #252
Opened 2024-08-14 06:50 UTC by tschumpr

Resolves #245 
Resolves #209 
Resolves #211 

Folgeissue für fehlschlagenden Test: https://github.com/GeoWerkstatt/geopilot/issues/255

2024-08-19 12:10 UTC, danjov approved these changes
lgtm

2024-08-19 12:10 UTC, danjov commented on src/Geopilot.Frontend/vite.config.js
> -import fs from "fs";
Q: Weshalb der Switch zu `http`?

2024-08-19 15:10 UTC, Philippluca requested changes
Das meiste sieht super aus. Styling muss ich mal auf einer laufenden Instanz beurteilen.

2024-08-19 15:10 UTC, Philippluca commented on src/Geopilot.Frontend/src/components/appSettings/appSettingsInterface.ts
> +import { useContext } from "react";
Q: Können wir hier beim Fetch detektieren, wenn client-settings.json nicht dem Schema entspricht und auf die konsole loggen?

2024-08-19 15:10 UTC, Philippluca commented on src/Geopilot.Frontend/src/components/header/header.tsx
> +          <Box sx={{ display: "flex", flexDirection: "row", alignItems: "center", padding: "5px 0" }}>
PP: Styling in Komponenten auslagern, welche man wiederverwenden kann. z.B. HeaderMenu etc.

2024-08-20 06:55 UTC, Philippluca commented on src/Geopilot.Frontend/index.html
> +        <link rel="icon" href="/emblem-black.png"/>
Beim start vom Container werden alle Assest aus dem gemounteten /public directory in den static files folder der .NET API gepackt. Bedeutet, dass ein File welches nicht überschrieben wird, weiterhin unverändert verfügbar bleibt. 

https://github.com/GeoWerkstatt/geopilot/blob/c32f270906272e8d35523f77be280957b6dfafa0/docker-entrypoint.sh#L11

2024-08-20 07:02 UTC, Philippluca commented on CHANGELOG.md
> +- Redesigned complete application.
Ok. Nur um sicher zu stellen, dass es nicht vergessen geht. Lieber mal zu viel aufschreiben und dann minimieren.

2024-08-20 07:04 UTC, Philippluca commented on src/Geopilot.Frontend/cypress/e2e/app.cy.js
> +    cy.intercept("/api/v1/user/auth", {
Das was ich von einer laufenden API ohne konfigurierter Parameter erwarte. Ich denke da kommt zwar ein valides Objekt zurück, welches jedoch leere strings definiert.

2024-09-02 15:20 UTC, Philippluca approved these changes
LGTM

2024-09-02 15:20 UTC, merged