Return relevant items in STAC search
GeoWerkstatt/geopilot pull request #267
Opened 2024-08-21 12:53 UTC by domi-b

Resolves #263

2024-08-21 12:59 UTC, Philippluca submitted a review, later dismissed
Q: Gibt es für STAC keine Tests?

2024-08-21 13:09 UTC, domi-b commented
Aktuell haben keine STAC-Tests ausser für den StacConverter.

2024-08-22 08:47 UTC, Philippluca commented
@domi-b Ev könntest du mit https://github.com/Terradue/DotNetStac?tab=readme-ov-file#deserialize-and-validate-your-first-catalog 1,2 Tests ergänzen.

2024-08-26 08:26 UTC, danjov requested changes

2024-08-26 08:26 UTC, danjov commented on tests/Geopilot.Api.Test/Geopilot.Api.Test.csproj
> +    <NoWarn>CA1861</NoWarn>
REQ: Die Rule im entsprechenden [`.editorconfig`-File](https://github.com/GeoWerkstatt/geopilot/blob/main/tests/.editorconfig) ausschalten.

2024-08-26 08:42 UTC, danjov approved these changes

2024-08-26 08:47 UTC, Philippluca approved these changes

2024-08-26 10:30 UTC, merged