Authentication in Swagger UI & documentation
GeoWerkstatt/geopilot pull request #270
Opened 2024-08-28 09:03 UTC by domi-b

Resolves #162

2024-08-28 09:10 UTC, danjov approved these changes

2024-08-28 13:57 UTC, Philippluca requested changes

2024-08-28 13:57 UTC, Philippluca commented on README.md
> +Diese werden beispielsweise bei den OIDC Scopes `openid`, `profile` und `email` mitgeliefert.
PP: Link zu OpenID Spec. einfügen. https://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims

2024-08-28 13:57 UTC, Philippluca commented on README.md
> +Der Wert `ApiScope` in den Appsettings kann dazu verwendet werden, um diesen im Swagger UI zur Auswahl anzuzeigen.
PP: Etwas exakter formulieren, wann hier die Problematik auftritt. Ohne OAuth2.0 Verständnis fehlt hier einiges.
```suggestion
Abhängig vom Identity Provider wird die Audience (aud) automatisch gesetzt, sofern ein passender Scope verwendet wird. Der benötigte Scope kann in den Appsettings under `ApiScope` gesetzt werden, um diesen im Swagger UI zur Auswahl anzuzeigen.
```

2024-08-28 13:57 UTC, Philippluca commented on README.md
> +    "ApiOrigin": "https://localhost:7188" // Swagger UI origin
Q: Gibt es hier keine Möglichkeit, dies nicht zu konfigurieren & dass das SwaggerUI das selbst mit befüllt.?

2024-08-28 13:57 UTC, Philippluca commented on src/Geopilot.Api/Program.cs
> +    });
PP: Konfiguration vom SwaggerUI in Funktion extrahieren

2024-08-28 13:57 UTC, Philippluca commented on src/Geopilot.Api/Program.cs
> +                RefreshUrl = new Uri(builder.Configuration["Auth:TokenUrl"] !),
REQ:  Konfigurationen optional gestalten. Sofern nicht explizit alle definiert, einen OpenID Connect Discovery Endpoint anbieten. So kann man sich auch bei nicht abschliessend Dokumentierten Instanzen einloggen. Wenn auch mit mehraufwand.

2024-08-29 07:47 UTC, domi-b commented on README.md
> +    "ApiOrigin": "https://localhost:7188" // Swagger UI origin
Ich habe es jetzt so angepasst, dass nur die ApiOrigin zusätzlich zu den bestehenden Werten angegeben werden muss, die anderen neuen Werte sind jetzt optional (mit OIDC discovery).

2024-08-29 14:45 UTC, Philippluca approved these changes

2024-09-02 12:31 UTC, Philippluca approved these changes

2024-09-02 13:43 UTC, merged